### PR TITLE
Order customizations log by created_at when computing time-spent

### PR DESCRIPTION
**Pull request by fabubaker**
Previously when computing the minutes and sessions for time-spent, the select statement would order the customizations_log by `_id`. 

This patch orders the log by `created_at`, which makes more sense semantically.

### CODE REVIEW

**Comment by fabubaker** [comment]
We actually don't have any indices for the `customizations_log` table at all, so there are no performance tradeoffs. 

This is just to match the semantics of the original time-spent code and also to prevent coupling the time-spent computation against an unrelated `_id` column.

**Comment by hammady** [comment]
I thought `_id` is the primary key. Why it is not?

**Comment by fabubaker** [comment]
It was defined that way since the beginning:
```
CREATE TABLE IF NOT EXISTS r${reviewId}_customizations_log (
        _id INTEGER NOT NULL DEFAULT nextval('r${reviewId}_customizations_log_id_seq'),
        ...
);
```

**Comment by hammady** [comment]
I know it was from the beginning. I'm trying to understand why was that, could be by mistake.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by fabubaker** [comment]
So what's the blocking issue for this PR?

**Comment by hammady** [comment]
If we change `_id` to be the primary key, then we can keep it. Not having any primary key looks like a mistake to me. Why we have `_id` in the first place? (I know it is me :D)

**Comment by hammady** [comment]
Actually `_id` does not have to be a primary key to keep it.

**Comment by fabubaker** [comment]
After doing some research, `ORDER BY` will only use an index if it's a B-Tree. The benchmarks also reflect significant performance gains:

```
rayyan_store=# EXPLAIN ANALYZE SELECT * FROM test_table ORDER BY created_at;
                                                         QUERY PLAN                                                         
----------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=292856.69..297856.69 rows=2000000 width=8) (actual time=858.007..1198.373 rows=2000000 loops=1)
   Sort Key: created_at
   Sort Method: external merge  Disk: 35168kB
   ->  Seq Scan on test_table  (cost=0.00..28850.00 rows=2000000 width=8) (actual time=0.023..134.435 rows=2000000 loops=1)
 Planning time: 0.099 ms
 Execution time: 1258.774 ms
(6 rows)

rayyan_store=# CREATE INDEX test_idx ON test_table using BTREE (created_at);
CREATE INDEX
rayyan_store=# EXPLAIN ANALYZE SELECT * FROM test_table ORDER BY created_at;
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using test_idx on test_table  (cost=0.43..80718.76 rows=2000000 width=8) (actual time=0.022..594.760 rows=2000000 loops=1)
 Planning time: 0.153 ms
 Execution time: 656.565 ms
(3 rows)


```

So I think the best thing to do here is set `_id` to be a primary key and create a b-tree index for `created_at` and use it to sort.

**Comment by hammady** [comment]
But adding an index on `created_at` will impact the insertion time, which is what we thrive to make the fastest.

**Comment by fabubaker** [comment]
> But adding an index on created_at will impact the insertion time, which is what we thrive to make the fastest.
But if we make `_id` the primary key, won't we suffer the same write penalty due to the primary key index?

If we are choosing to optimize our writes, then it's probably best to omit any indices, at the cost of endpoints like `time-spent`, `last-customization` and `topKUsersLabels` taking a performance hit (they all perform a sort). 

Furthermore, If we are omitting indices, then we might as well sort by `created_at` since there is no difference in performance compared to `_id`.

**Comment by hammady** [comment]
Indexing on `_id` as the primary key is a separate issue that needs to be addressed, and we already did that. Now the new state is that we have an indexed column (`_id`) and another one which is not indexed (`created_at`). I cannot see any advantage to use the latter for sorting as it has the same order as the former. Then why use it while it is slower?

**Comment by hammady** [comment]
@fabubaker Any update on this?

**Comment by fabubaker** [comment]
I'm thinking of abandoning this PR. Merging it requires adding an extra index, which is too much just for the sake of better semantics.

**Pull request closed without merging**
