### PR TITLE
Add new skaffold profile and chart for running tests

### PR DESCRIPTION
**Pull request by hammady**
- This adds a new skaffold profile: test
- It also adds a new chart: rayyan-store-tests
- Test reports and coverage will be generated in the `/home/test-reports` directory and mounted on the host node

### CODE REVIEW

**Comment by fabubaker** [comment]
Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.

**Comment by hammady** [comment]
> Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.

Why can't we merge both test commands? I wonder how would this work with skaffold and the tests chart, should we create another profile for `test:ci`? Does it harm to always generate reports?

**Comment by hammady** [comment]
> > Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.
> 
> Why can't we merge both test commands? I wonder how this would work with skaffold and the tests chart, should we create another profile for `test:ci`? Does it harm to always generate reports?

I have merged both to simplify the invocation. However, when this runs on CI, we should mount a volume to capture the generated reports and publish them.

**Comment by fabubaker** [comment]
> > > Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.
> > 
> > 
> > Why can't we merge both test commands? I wonder how this would work with skaffold and the tests chart, should we create another profile for `test:ci`? Does it harm to always generate reports?
> 
> I have merged both to simplify the invocation. However, when this runs on CI, we should mount a volume to capture the generated reports and publish them.

I guess there's no real downside to generating reports, but at the least it might be a good idea to add `junit.xml` and `coverage/` folders to .gitignore.

**Review by fabubaker — APPROVED** [review]

**Comment by hammady** [comment]
> > > > Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.
> > > 
> > > 
> > > Why can't we merge both test commands? I wonder how this would work with skaffold and the tests chart, should we create another profile for `test:ci`? Does it harm to always generate reports?
> > 
> > 
> > I have merged both to simplify the invocation. However, when this runs on CI, we should mount a volume to capture the generated reports and publish them.
> 
> ~I guess there's no real downside to generating reports, but at the least it might be a good idea to add `junit.xml` and `coverage/` folders to .gitignore.~ NVM, I forgot we're running these as Jobs.

I have pushed a commit that mounts 2 hostPaths to capture test and coverage results. I would have loved to mount only one volume, but I couldn't figure out how to customize the output file locations in the `jest` command.

**Comment by fabubaker** [comment]
> > > > > Now, running `npm run test:ci` publishes test results and coverage directory in the root folder as `junit.xml` and `coverage/`.
> > > > 
> > > > 
> > > > Why can't we merge both test commands? I wonder how this would work with skaffold and the tests chart, should we create another profile for `test:ci`? Does it harm to always generate reports?
> > > 
> > > 
> > > I have merged both to simplify the invocation. However, when this runs on CI, we should mount a volume to capture the generated reports and publish them.
> > 
> > 
> > ~I guess there's no real downside to generating reports, but at the least it might be a good idea to add `junit.xml` and `coverage/` folders to .gitignore.~ NVM, I forgot we're running these as Jobs.
> 
> I have pushed a commit that mounts 2 hostPaths to capture test and coverage results. I would have loved to mount only one volume, but I couldn't figure out how to customize the output file locations in the `jest` command.

Test reports and coverage will now be generated in the `test-reports` directory:
```
root@6fa8e15208e3:/home/test-reports# ls -l
total 104
-rw-r--r-- 1 root root  5394 Oct 21 07:17 base.css
-rw-r--r-- 1 root root  2387 Oct 21 07:17 block-navigation.js
-rw-r--r-- 1 root root  6899 Oct 21 07:17 cobertura-coverage.xml
-rw-r--r-- 1 root root   540 Oct 21 07:17 favicon.png
-rw-r--r-- 1 root root  4200 Oct 21 07:17 index.html
-rw-r--r-- 1 root root  3197 Oct 21 07:17 junit.xml
-rw-r--r-- 1 root root 30938 Oct 21 07:17 migrator.ts.html
-rw-r--r-- 1 root root   676 Oct 21 07:17 prettify.css
-rw-r--r-- 1 root root 17590 Oct 21 07:17 prettify.js
-rw-r--r-- 1 root root   209 Oct 21 07:17 sort-arrow-sprite.png
-rw-r--r-- 1 root root  5278 Oct 21 07:17 sorter.js
```

**Review by fabubaker — APPROVED** [review]

**Pull request merged**
