### PR TITLE
Stringify label strings before inserting into postgres

### LINKED ISSUE #59: Malformed RayyanStore query
There seems to be a problem in some of the queries (could be incorrect character escaping).

Checking one of the postgresql log I saw this:

```
2019-03-29 14:53:27 UTC-5c9e30df.89864-ERROR:  malformed array literal: "{219 patients aged over 65 referred consecutively to a geriatric hospital,}"
2019-03-29 14:53:27 UTC-5c9e30df.89864-DETAIL:  Unexpected "}" character.
2019-03-29 14:53:27 UTC-5c9e30df.89864-CONTEXT:  SQL statement "UPDATE r56174
	          SET customizations = jsonb_set(
	            jsonb_set(coalesce(customizations, '{"labels": {}, "included": {}}'::jsonb), ('{labels'||user_id||'}')::text[],
	              jsonb_set(coalesce(customizations -> ('labels'||user_id), '{}'::jsonb), ('{'||key||'}')::text[], '1'::jsonb)
	            ), ('{labels,'||key||'}')::text[], '1'::jsonb)
	          WHERE _id = article_id"
	PL/pgSQL function r56174_insert_customization(integer,integer,text,jsonb) line 18 at SQL statement
	SQL statement "SELECT r56174_insert_customization(article_id, user_id, key, value)"
	PL/pgSQL function r56174_update_customization(boolean,integer,integer,text,jsonb) line 6 at PERFORM
2019-03-29 14:53:27 UTC-5c9e30df.89864-STATEMENT:  SELECT r56174_update_customization($1, $2, $3, $4, $5)
2019-03-29 14:53:27 UTC-5c9e30df.89864-LOG:  disconnection: session time: 0:02:15.530 user=rayyan database=postgres host=10.240.0.27 port=20610
```

### PR DESCRIPTION
**Pull request by fabubaker**
In `CREATE OR REPLACE FUNCTION r${reviewId}_insert_customization(article_id INTEGER, user_id INTEGER, key TEXT, value JSONB DEFAULT '1')`, an array literal is built by concatenating `{`  + `key` + `}`.

However the array literal becomes malformed if:
* there is a `,` at the end of `key` (the array literal becomes `"{key,}"`)
* there is a ` " ` (double quote) in `key` (the array literal becomes `"{"key}"`)

Both problems can be fixed by calling `JSON.stringify` on `key` before inserting into postgres, effectively wrapping `key` in quotes as well as escaping any double quotes.

In conjunction with https://github.com/qcri/rayyan/pull/497, this fixes #59.

### CODE REVIEW

**Comment by hammady** [comment]
LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.

**Comment by fabubaker** [comment]
> LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.

Right, I meant it converts `"label"` to `"\"label\""`, which is just escaping quotes I guess...

**Comment by hammady** [comment]
> > LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.
> 
> Right, I meant it converts `"label"` to `"\"label\""`, which is just escaping quotes I guess...

This is a distraction. All strings have double quotes only when coded in the source. However, the quotes are not part of the string, so it is wrong to say this fix wraps by quotes. You can say: converts `label"suffix` to `label\"suffix`.

**Comment by fabubaker** [comment]
> > > LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.
> > 
> > 
> > Right, I meant it converts `"label"` to `"\"label\""`, which is just escaping quotes I guess...
> 
> This is a distraction. All strings have double quotes only when coded in the source. However, the quotes are not part of the string, so it is wrong to say this fix wraps by quotes. You can say: converts `label"suffix` to `label\"suffix`.

Maybe my intention is getting lost in translation, but isn't `JSON.stringify` literally wrapping the input in quotes:

image

**Comment by hammady** [comment]
> > > > LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.
> > > 
> > > 
> > > Right, I meant it converts `"label"` to `"\"label\""`, which is just escaping quotes I guess...
> > 
> > 
> > This is a distraction. All strings have double quotes only when coded in the source. However, the quotes are not part of the string, so it is wrong to say this fix wraps by quotes. You can say: converts `label"suffix` to `label\"suffix`.
> 
> Maybe my intention is getting lost in translation, but isn't `JSON.stringify` literally wrapping the input in quotes:
> 
> image

Then this is not what we need, why wrapping into extra quotes? We are not stringifying objects, we already assume strings, so we only need to escape quotes not stringify again.

**Comment by fabubaker** [comment]
> > > > > LGTM. However, in the description, you mentioned that it wraps the string into quotations which is not true.
> > > > 
> > > > 
> > > > Right, I meant it converts `"label"` to `"\"label\""`, which is just escaping quotes I guess...
> > > 
> > > 
> > > This is a distraction. All strings have double quotes only when coded in the source. However, the quotes are not part of the string, so it is wrong to say this fix wraps by quotes. You can say: converts `label"suffix` to `label\"suffix`.
> > 
> > 
> > Maybe my intention is getting lost in translation, but isn't `JSON.stringify` literally wrapping the input in quotes:
> > image
> 
> Then this is not what we need, why wrapping into extra quotes? We are not stringifying objects, we already assume strings, so we only need to escape quotes not stringify again.

Wrapping in extra quotes is required because of the concatenation happening in postgres to form the array literal. Note that in postgres `{label}` is equivalent to `{"label"}`.
So for eg, if the user enters `label,` in the input box, the array literal becomes `{label,}` which is malformed. Wrapping it in quotes results in the array literal becoming `{"label,"}`, which is the behaviour we want.

**Pull request merged**
